# Generated by Django 3.0.5 on 2021-02-19 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='search',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='search',
        ),
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(default='noname', max_length=200),
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.CharField(default='noslag', max_length=200),
        ),
        migrations.AddField(
            model_name='genre',
            name='name',
            field=models.CharField(default='noname', max_length=200),
        ),
        migrations.AddField(
            model_name='genre',
            name='slug',
            field=models.CharField(default='noslag', max_length=200),
        ),
        migrations.AddField(
            model_name='titles',
            name='description',
            field=models.TextField(default='textfield'),
        ),
    ]
