# Generated by Django 3.0.5 on 2021-02-25 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210225_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='slug',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
