# Generated by Django 3.0.5 on 2021-02-27 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210227_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titles',
            name='year',
            field=models.DateField(null=True, verbose_name='Дата публикации'),
        ),
    ]
