# Generated by Django 3.0.5 on 2021-02-19 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorize', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preuser',
            old_name='mail',
            new_name='email',
        ),
    ]
